name: CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0

      - name: set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.5

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.3.3

      - name: Build 
        run: ./gradlew gradle-plugin:assemble

      - name: Lint
        run: ./gradlew detekt

      - name: Run Tests
        run: ./gradlew test

      - name: Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODE_COV_TOKEN  }}
